OPTIONS = -c

CC = gcc
FLAGS = -Wall -Wextra -Werror

NAME = ft_display_file

OBJ = ft_display_file.o 

all:
		$(CC) $(FLAGS) ft_display_file.c -o $(NAME)
clean:
		rm -f $(OBJ)

fclean: clean
		rm -f $(NAME)

re: fclean all